### ISSUE TITLE
ote find --root $TASK_ALGO_DIR is giving empty list

### ISSUE THREAD

**Issue by aks473** [open-edge-platform/training_extensions#1376]
Followed instructions as specified at https://github.com/openvinotoolkit/training_extensions/blob/develop/QUICK_START_GUIDE.md 

When i run  -> ote find --root $TASK_ALGO_DIR , i get an empty list [] as response 
and 
on executing  -> ote train ./external/mmdetection/configs/ote/custom-object-detection/gen3_mobilenetV2_ATSS/template.yaml --help 
i get following error:

(detection) aks@aks-VirtualBox:~/Documents/intel/training_extensions$ ote train ./external/mmdetection/configs/ote/custom-object-detection/gen3_mobilenetV2_ATSS/template.yaml --help
Traceback (most recent call last):
  File "/home/aks/Documents/intel/training_extensions/venv2/bin/ote", line 33, in <module>
    sys.exit(load_entry_point('ote-cli', 'console_scripts', 'ote')())
  File "/home/aks/Documents/intel/training_extensions/ote_cli/ote_cli/tools/ote.py", line 67, in main
    globals()[f"ote_{name}"]()
  File "/home/aks/Documents/intel/training_extensions/ote_cli/ote_cli/tools/train.py", line 119, in main
    args, template, hyper_parameters = parse_args()
  File "/home/aks/Documents/intel/training_extensions/ote_cli/ote_cli/tools/train.py", line 59, in parse_args
    template = find_and_parse_model_template(parsed.template)
  File "/home/aks/Documents/intel/training_extensions/ote_cli/ote_cli/registry/registry.py", line 122, in find_and_parse_model_template
    return Registry(".").get(path_or_id)
  File "/home/aks/Documents/intel/training_extensions/ote_cli/ote_cli/registry/registry.py", line 96, in get
    raise ValueError(
ValueError: Could not find a template with ./external/mmdetection/configs/ote/custom-object-detection/gen3_mobilenetV2_ATSS/template.yaml in registry.

Where are these template.yaml , it's not in the code or any of the directory

**Comment by goodsong81** [comment]
Hello, sorry for inconvenience. We are in a process of refactoring.
Working models are located in external/model-preparation-algorithm/.

**Comment by yunchu** [comment]
Hi @aks473, 
Thanks for your sharing the issue.
There was some update (#1397) on the doc. please check this out and let us know the result.

**Comment by aks473** [comment]
Hi @yunchu ,
The update looks good, that's exactly what i was doing after the comment received from @goodsong81 .
Appreciate it. 
Thanks
