### ISSUE TITLE
Detector training with OTX 1.2 fails with 'No module named mmcv._ext' exception

### ISSUE THREAD

**Issue by asutic** [open-edge-platform/training_extensions#2094]
**Describe the bug**

I'm following the documentation on object detection to use 1.12 OTX release. Everything goes smoothly until I try to train the detector in the created environment. At that point, issue with mmcv occurs.

`
(.otx) asutic@asutic-desk3:~/Work/otx_tutorial/otx-workspace-DETECTION$ otx train --output outputs --workspace outputs/logs --train-data-root ../data/wgisd
[*] Detected dataset format: coco
WARNING:root:File '/home/asutic/Work/careai/otx_tutorial/otx-workspace-DETECTION/../data/wgisd/annotations/train_polygons_instances.json' was skipped, could't match this file with any of these tasks: coco_instances,coco_person_keypoints,coco_captions,coco_labels,coco_image_info,coco_panoptic,coco_stuff
WARNING:root:File '/home/asutic/Work/careai/otx_tutorial/otx-workspace-DETECTION/../data/wgisd/annotations/test_polygons_instances.json' was skipped, could't match this file with any of these tasks: coco_instances,coco_person_keypoints,coco_captions,coco_labels,coco_image_info,coco_panoptic,coco_stuff
[*] Found validation data in your dataset in /home/asutic/Work/careai/otx_tutorial/otx-workspace-DETECTION/../data/wgisd. It'll be used as validation data.
[*] Update data configuration file to: outputs/logs/data.yaml
/home/asutic/Work/openvinotoolkit/training_extensions/.otx/lib/python3.10/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
WARNING:root:Not implemented: Found potentially conflicting source types with labels: stuff, instances. Only one type will be used: instances
WARNING:root:Not implemented: conflicting source '/home/asutic/Work/careai/otx_tutorial/otx-workspace-DETECTION/outputs/logs/splitted_dataset/train/annotations/stuff_train.json' is skipped.
WARNING:root:Not implemented: Found potentially conflicting source types with labels: stuff, instances. Only one type will be used: instances
WARNING:root:Not implemented: conflicting source '/home/asutic/Work/careai/otx_tutorial/otx-workspace-DETECTION/outputs/logs/splitted_dataset/val/annotations/stuff_val.json' is skipped.
/home/asutic/Work/openvinotoolkit/training_extensions/.otx/lib/python3.10/site-packages/otx/api/entities/shapes/shape.py:179: UserWarning: Rectangle coordinates (x=-4.882812572759576e-05, y=0.3860512981484661) are out of bounds, a normalized coordinate system is assumed. All coordinates are expected to be in range (0,1).
  warnings.warn(
/home/asutic/Work/openvinotoolkit/training_extensions/.otx/lib/python3.10/site-packages/otx/api/entities/shapes/rectangle.py:60: UserWarning: Rectangle coordinates are invalid : x1=-4.882812572759576e-05, y1=0.3860512981484661, x2=0.042451173067092896, y2=0.5069523737980769
  warnings.warn(
/home/asutic/Work/openvinotoolkit/training_extensions/.otx/lib/python3.10/site-packages/otx/api/entities/shapes/shape.py:179: UserWarning: Rectangle coordinates (x=-4.882812572759576e-05, y=0.5384981595552885) are out of bounds, a normalized coordinate system is assumed. All coordinates are expected to be in range (0,1).
  warnings.warn(
/home/asutic/Work/openvinotoolkit/training_extensions/.otx/lib/python3.10/site-packages/otx/api/entities/shapes/rectangle.py:60: UserWarning: Rectangle coordinates are invalid : x1=-4.882812572759576e-05, y1=0.5384981595552885, x2=0.05464843660593033, y2=0.6270988939445971
  warnings.warn(
/home/asutic/Work/openvinotoolkit/training_extensions/.otx/lib/python3.10/site-packages/otx/api/entities/shapes/shape.py:179: UserWarning: Rectangle coordinates (x=-4.882812572759576e-05, y=0.2835018395504235) are out of bounds, a normalized coordinate system is assumed. All coordinates are expected to be in range (0,1).
  warnings.warn(
/home/asutic/Work/openvinotoolkit/training_extensions/.otx/lib/python3.10/site-packages/otx/api/entities/shapes/rectangle.py:60: UserWarning: Rectangle coordinates are invalid : x1=-4.882812572759576e-05, y1=0.2835018395504235, x2=0.018051758408546448, y2=0.40729671939388734
  warnings.warn(
Traceback (most recent call last):
  File "/home/asutic/Work/openvinotoolkit/training_extensions/.otx/bin/otx", line 8, in <module>
    sys.exit(main())
  File "/home/asutic/Work/openvinotoolkit/training_extensions/.otx/lib/python3.10/site-packages/otx/cli/tools/cli.py", line 77, in main
    results = globals()[f"otx_{name}"]()
  File "/home/asutic/Work/openvinotoolkit/training_extensions/.otx/lib/python3.10/site-packages/otx/cli/tools/train.py", line 165, in main
    return train(exit_stack)
  File "/home/asutic/Work/openvinotoolkit/training_extensions/.otx/lib/python3.10/site-packages/otx/cli/tools/train.py", line 196, in train
    task_class = get_impl_class(template.entrypoints.base)
  File "/home/asutic/Work/openvinotoolkit/training_extensions/.otx/lib/python3.10/site-packages/otx/cli/utils/importing.py", line 40, in get_impl_class
    task_impl_module = importlib.import_module(task_impl_module_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/asutic/Work/openvinotoolkit/training_extensions/.otx/lib/python3.10/site-packages/otx/algorithms/detection/adapters/mmdet/__init__.py", line 7, in <module>
    from . import models
  File "/home/asutic/Work/openvinotoolkit/training_extensions/.otx/lib/python3.10/site-packages/otx/algorithms/detection/adapters/mmdet/models/__init__.py", line 6, in <module>
    from . import backbones, dense_heads, detectors, heads, losses, necks, roi_heads
  File "/home/asutic/Work/openvinotoolkit/training_extensions/.otx/lib/python3.10/site-packages/otx/algorithms/detection/adapters/mmdet/models/backbones/__init__.py", line 6, in <module>
    from . import imgclsmob
  File "/home/asutic/Work/openvinotoolkit/training_extensions/.otx/lib/python3.10/site-packages/otx/algorithms/detection/adapters/mmdet/models/backbones/imgclsmob.py", line 10, in <module>
    from mmdet.models.builder import BACKBONES
  File "/home/asutic/Work/openvinotoolkit/training_extensions/.otx/lib/python3.10/site-packages/mmdet/models/__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/home/asutic/Work/openvinotoolkit/training_extensions/.otx/lib/python3.10/site-packages/mmdet/models/backbones/__init__.py", line 2, in <module>
    from .csp_darknet import CSPDarknet
  File "/home/asutic/Work/openvinotoolkit/training_extensions/.otx/lib/python3.10/site-packages/mmdet/models/backbones/csp_darknet.py", line 11, in <module>
    from ..utils import CSPLayer
  File "/home/asutic/Work/openvinotoolkit/training_extensions/.otx/lib/python3.10/site-packages/mmdet/models/utils/__init__.py", line 13, in <module>
    from .point_sample import (get_uncertain_point_coords_with_randomness,
  File "/home/asutic/Work/openvinotoolkit/training_extensions/.otx/lib/python3.10/site-packages/mmdet/models/utils/point_sample.py", line 3, in <module>
    from mmcv.ops import point_sample
  File "/home/asutic/Work/openvinotoolkit/training_extensions/.otx/lib/python3.10/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "/home/asutic/Work/openvinotoolkit/training_extensions/.otx/lib/python3.10/site-packages/mmcv/ops/active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "/home/asutic/Work/openvinotoolkit/training_extensions/.otx/lib/python3.10/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
**ModuleNotFoundError: No module named 'mmcv._ext'**
` 

**Steps to Reproduce**

1. Set up virtual environment per https://openvinotoolkit.github.io/training_extensions/latest/guide/get_started/quick_start_guide/installation.html. Use the PyPi OTX module.
2. Follow the instructions from https://openvinotoolkit.github.io/training_extensions/latest/guide/tutorials/base/how_to_train/detection.html.
3. The issues reproduces at the 'otx train' stage.

**Environment:**

- OS: Linux Ubuntu 20.04.5
- Framework version: PyTorch 1.13.1+cu117
- Python version: 3.10.9
- OpenVINO version: 2022.3.0
- CUDA/cuDNN version: 11.7
- GPU model and memory: NVIDIA GeForce 2080 Ti, 12 GB

The training of the classification model doesn't cause any similar issue in the same environment.

Is there anything new in the OTX 1.12 I should know about? Do I need to update the installation process or change something in the workspace setup?

**Comment by eugene123tw** [comment]
@goodsong81 Could you take a look? Thanks!

**Comment by goodsong81** [comment]
It seems that the mmcv was not well built.
Could you try `pip install --no-cache-dir mmcv-full==1.7.0` and then run train again?

**Comment by asutic** [comment]
Thanks, @goodsong81. I tried the trick that you suggested, but that didn't resolve the problem. Below is the exact list of steps I used to create new clean environment (note: the dataset has been already arranged previously to the COCO format). Do you have other ideas I should try to get this working?

python3.8 -m venv .otx_py38
source .otx_py38/bin/activate
pip install --upgrade pip
export CUDA_HOME=/usr/local/cuda-11.7
git remote update
git checkout -b 1.2.1rc2 1.2.1rc2
pip install torch==1.13.1 torchvision==0.14.1 --extra-index-url https://download.pytorch.org/whl/cu117
pip install --no-cache-dir mmcv-full==1.7.0
pip install -e .[full]
otx build Custom_Object_Detection_Gen3_ATSS --train-data-roots data/wgisd
cd otx-workspace-DETECTION/
otx train --output outputs --workspace outputs/logs --train-data-roots splitted_dataset/train --val-data-roots splitted_dataset/val

**Comment by eugene123tw** [comment]
@asutic Could you try this?

* create a new env in Python 3.10 and activate it
* export CUDA_HOME=/usr/local/cuda-11.7
* pip install tox
* tox devenv venv/otx -e pre-merge-all-py310
* source venv/otx/bin/activate

**Comment by goodsong81** [comment]
In addition to the method that @eugene123tw proposed, please try the following commands.

- `pip install mmcv-full @ https://download.openmmlab.com/mmcv/dist/cu117/torch1.13.0/mmcv_full-1.7.0-cp38-cp38-manylinux1_x86_64.whl`
- Or, `pip install  --no-cache-dir mmcv-full==1.7.0 -f https://download.openmmlab.com/mmcv/dist/cu117/torch1.13/index.html`

**Comment by asutic** [comment]
Thank you, @eugene123tw and @goodsong81. The TOX method solved my issues. I'm finally able to see the detection model training running.

**Comment by sungmanc** [comment]
> Thank you, @eugene123tw and @goodsong81. The TOX method solved my issues. I'm finally able to see the detection model training running.

It seems that the issue was solved. So, close this issue.
