### ISSUE TITLE
Cannot train with Semisupervised train type.

### ISSUE THREAD

**Issue by JihwanEom** [open-edge-platform/training_extensions#2099]
**Describe the bug**

`otx train` with Semisupervised train type throws `TypeError: DataLoader.__init__() got an unexpected keyword argument 'unlabeled'`.

**Steps to Reproduce**

```
otx build --task classification --train-type Semisupervised
cd otx-workspace-CLASSIFICATION
(set data path in data.yaml, include unlabeled data)
otx train
```

**Traceback**
```
(otx-vit) jeom@jeom-desktop:~/ws/otx-vit/otx-workspace-CLASSIFICATION$ otx train
[*] Update data configuration file to: data.yaml
/home/jeom/anaconda3/envs/otx-vit/lib/python3.10/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
/home/jeom/anaconda3/envs/otx-vit/lib/python3.10/site-packages/albumentations/augmentations/geometric/functional.py:7: DeprecationWarning: Please use `gaussian_filter` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.
  from scipy.ndimage.filters import gaussian_filter
/home/jeom/anaconda3/envs/otx-vit/lib/python3.10/site-packages/sklearn/utils/multiclass.py:14: DeprecationWarning: Please use `spmatrix` from the `scipy.sparse` namespace, the `scipy.sparse.base` namespace is deprecated.
  from scipy.sparse.base import spmatrix
/home/jeom/anaconda3/envs/otx-vit/lib/python3.10/site-packages/sklearn/utils/optimize.py:18: DeprecationWarning: Please use `line_search_wolfe2` from the `scipy.optimize` namespace, the `scipy.optimize.linesearch` namespace is deprecated.
  from scipy.optimize.linesearch import line_search_wolfe2, line_search_wolfe1
/home/jeom/anaconda3/envs/otx-vit/lib/python3.10/site-packages/sklearn/utils/optimize.py:18: DeprecationWarning: Please use `line_search_wolfe1` from the `scipy.optimize` namespace, the `scipy.optimize.linesearch` namespace is deprecated.
  from scipy.optimize.linesearch import line_search_wolfe2, line_search_wolfe1
/home/jeom/anaconda3/envs/otx-vit/lib/python3.10/site-packages/albumentations/augmentations/transforms.py:14: DeprecationWarning: Please use `gaussian_filter` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.
  from scipy.ndimage.filters import gaussian_filter
/home/jeom/anaconda3/envs/otx-vit/lib/python3.10/site-packages/mmcv/utils/registry.py:277: DeprecationWarning: The old API of register_module(module, force=False) is deprecated and will be removed, please use the new API register_module(name=None, force=False, module=None) instead.
  warnings.warn(
/home/jeom/anaconda3/envs/otx-vit/lib/python3.10/site-packages/openvino/pyopenvino/__init__.py:10: FutureWarning: The module is private and following namespace `pyopenvino` will be removed in the future
  warnings.warn(message="The module is private and following namespace " "`pyopenvino` will be removed in the future", category=FutureWarning)
/home/jeom/anaconda3/envs/otx-vit/lib/python3.10/site-packages/openvino/tools/mo/middle/passes/convert_data_type.py:43: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  'bool': (np.bool, 'BOOL', 'boolean'),
/home/jeom/anaconda3/envs/otx-vit/lib/python3.10/site-packages/defusedxml/__init__.py:30: DeprecationWarning: defusedxml.cElementTree is deprecated, import from defusedxml.ElementTree instead.
  from . import cElementTree
/home/jeom/anaconda3/envs/otx-vit/lib/python3.10/site-packages/openvino/tools/mo/utils/type_utils.py:12: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np_map_cast = {np.bool: lambda x: bool_cast(x),
/home/jeom/anaconda3/envs/otx-vit/lib/python3.10/site-packages/openvino/tools/mo/utils/type_utils.py:24: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.str: lambda x: np.str(x)}
/home/jeom/anaconda3/envs/otx-vit/lib/python3.10/site-packages/openvino/offline_transformations/__init__.py:10: FutureWarning: The module is private and following namespace `offline_transformations` will be removed in the future, use `openvino.runtime.passes` instead!
  warnings.warn(
INFO:nncf:NNCF initialized successfully. Supported frameworks detected: torch, onnx, openvino
2023-05-03 21:55:05,514 | INFO : Classification mode: multiclass
2023-05-03 21:55:05,515 | INFO : train()
2023-05-03 21:55:05,516 | INFO : Training seed was set to 5 w/ deterministic=False.
2023-05-03 21:55:05,518 | INFO : Try to create a 0 size memory pool.
2023-05-03 21:55:05,520 | INFO : configure!: training=True
2023-05-03 21:55:05,561 | INFO : 'in_channels' config in model.head is updated from -1 to 192
2023-05-03 21:55:05,561 | INFO : configure_data()
2023-05-03 21:55:05,561 | INFO : task config!!!!: training=True
2023-05-03 21:55:05,561 | INFO : train!
2023-05-03 21:55:05,561 | INFO : cfg.gpu_ids = range(0, 1), distributed = False
2023-05-03 21:55:05,580 | INFO : Environment info:
------------------------------------------------------------
sys.platform: linux
Python: 3.10.11 (main, Apr 20 2023, 19:02:41) [GCC 11.2.0]
CUDA available: True
GPU 0,1: NVIDIA GeForce RTX 3090
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.7, V11.7.64
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.13.1+cu117
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.5
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.14.1+cu117
OpenCV: 4.7.0
MMCV: 1.7.0
MMCV Compiler: GCC 9.4
MMCV CUDA Compiler: 11.1
MMClassification: 0.25.0+b43598c
------------------------------------------------------------

2023-05-03 21:55:06,400 - mmcv - INFO - load backbone in model from: https://download.openmmlab.com/mmclassification/v0/deit/deit-tiny_pt-4xb256_in1k_20220218-13b382a0.pth
load checkpoint from http path: https://download.openmmlab.com/mmclassification/v0/deit/deit-tiny_pt-4xb256_in1k_20220218-13b382a0.pth
Traceback (most recent call last):
  File "/home/jeom/anaconda3/envs/otx-vit/bin/otx", line 8, in <module>
    sys.exit(main())
  File "/home/jeom/ws/otx-vit/otx/cli/tools/cli.py", line 77, in main
    results = globals()[f"otx_{name}"]()
  File "/home/jeom/ws/otx-vit/otx/cli/tools/train.py", line 176, in main
    return train(exit_stack)
  File "/home/jeom/ws/otx-vit/otx/cli/tools/train.py", line 262, in train
    task.train(
  File "/home/jeom/ws/otx-vit/otx/algorithms/classification/task.py", line 208, in train
    results = self._train_model(dataset)
  File "/home/jeom/ws/otx-vit/otx/algorithms/classification/adapters/mmcls/task.py", line 413, in _train_model
    train_model(
  File "/home/jeom/anaconda3/envs/otx-vit/lib/python3.10/site-packages/mmcls/apis/train.py", line 125, in train_model
    data_loaders = [build_dataloader(ds, **train_loader_cfg) for ds in dataset]
  File "/home/jeom/anaconda3/envs/otx-vit/lib/python3.10/site-packages/mmcls/apis/train.py", line 125, in <listcomp>
    data_loaders = [build_dataloader(ds, **train_loader_cfg) for ds in dataset]
  File "/home/jeom/anaconda3/envs/otx-vit/lib/python3.10/site-packages/mmcls/datasets/builder.py", line 156, in build_dataloader
    data_loader = DataLoader(
TypeError: DataLoader.__init__() got an unexpected keyword argument 'unlabeled'
```

**Environment:**

Latest develop branch, commit hash: 6b390d1cde36fa08f66b4a1d0ab14e99b6e90ffa

**Comment by harimkang** [comment]
https://github.com/openvinotoolkit/training_extensions/pull/2102
I've created a PR to fix this. This is an issue since OTX1.2, and the resolved PR will be merged into OTX1.2.1 first and then into develop.

**Comment by harimkang** [comment]
https://github.com/openvinotoolkit/training_extensions/pull/2102 merged
