### ISSUE TITLE
Otx train on windows results in TypeError: cannot pickle '_thread.lock' object

### ISSUE THREAD

**Issue by cansik** [open-edge-platform/training_extensions#2162]
**Describe the bug**

I followed the [object detection](https://openvinotoolkit.github.io/training_extensions/latest/guide/tutorials/base/how_to_train/detection.html) example and tried to train YOLOX with the wgisd dataset. When running `otx train`, the multiprocessing dataloader is not able to pickle a `_thread.lock` object and throws an exception.

Is there an example on how to setup a Windows machine for otx or is it even supported? And how is it possible to restrict the dataloader to a single process?

```bash
2023-05-17 09:20:13,546 - mmdet - INFO - workflow: [('train', 1)], max: 200 epochs
2023-05-17 09:20:13,550 - mmdet - INFO - Checkpoints will be saved to F:\openvino\otx-workspace-DETECTION\outputs\20230517_092010_train\logs by HardDiskBackend.
2023-05-17 09:20:13,550 | INFO : cancel hook is initialized
2023-05-17 09:20:13,550 | INFO : logger in the runner is replaced to the MPA logger
[                                                  ] 0/58, elapsed: 0s, ETA:Traceback (most recent call last):
  File "C:\Users\demo\.conda\envs\openvino\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\demo\.conda\envs\openvino\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\demo\.conda\envs\openvino\Scripts\otx.exe\__main__.py", line 7, in <module>
  File "F:\openvino\training_extensions\otx\cli\tools\cli.py", line 77, in main
    results = globals()[f"otx_{name}"]()
  File "F:\openvino\training_extensions\otx\cli\tools\train.py", line 173, in main
    return train(exit_stack)
  File "F:\openvino\training_extensions\otx\cli\tools\train.py", line 259, in train
    task.train(
  File "F:\openvino\training_extensions\otx\algorithms\detection\task.py", line 192, in train
    results = self._train_model(dataset)
  File "F:\openvino\training_extensions\otx\algorithms\detection\adapters\mmdet\task.py", line 296, in _train_model
    train_detector(
  File "C:\Users\demo\.conda\envs\openvino\lib\site-packages\mmdet\apis\train.py", line 246, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "C:\Users\demo\.conda\envs\openvino\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "F:\openvino\training_extensions\otx\algorithms\common\adapters\mmcv\runner.py", line 75, in train
    self.call_hook("before_train_epoch")
  File "C:\Users\demo\.conda\envs\openvino\lib\site-packages\mmcv\runner\base_runner.py", line 317, in call_hook
    getattr(hook, fn_name)(self)
  File "C:\Users\demo\.conda\envs\openvino\lib\site-packages\mmdet\core\evaluation\eval_hooks.py", line 45, in before_train_epoch
    super().before_train_epoch(runner)
  File "C:\Users\demo\.conda\envs\openvino\lib\site-packages\mmcv\runner\hooks\evaluation.py", line 245, in before_train_epoch
    self.after_train_epoch(runner)
  File "C:\Users\demo\.conda\envs\openvino\lib\site-packages\mmcv\runner\hooks\evaluation.py", line 271, in after_train_epoch
    self._do_evaluate(runner)
  File "C:\Users\demo\.conda\envs\openvino\lib\site-packages\mmdet\core\evaluation\eval_hooks.py", line 60, in _do_evaluate
    results = single_gpu_test(runner.model, self.dataloader, show=False)
  File "C:\Users\demo\.conda\envs\openvino\lib\site-packages\mmdet\apis\test.py", line 27, in single_gpu_test
    for i, data in enumerate(data_loader):
  File "C:\Users\demo\.conda\envs\openvino\lib\site-packages\torch\utils\data\dataloader.py", line 435, in __iter__
    return self._get_iterator()
  File "C:\Users\demo\.conda\envs\openvino\lib\site-packages\torch\utils\data\dataloader.py", line 381, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\demo\.conda\envs\openvino\lib\site-packages\torch\utils\data\dataloader.py", line 1034, in __init__
    w.start()
  File "C:\Users\demo\.conda\envs\openvino\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\demo\.conda\envs\openvino\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\demo\.conda\envs\openvino\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\demo\.conda\envs\openvino\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\demo\.conda\envs\openvino\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle '_thread.lock' object
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\demo\.conda\envs\openvino\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\demo\.conda\envs\openvino\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
```

**Steps to Reproduce**

1. Follow the [example steps](https://openvinotoolkit.github.io/training_extensions/latest/guide/tutorials/base/how_to_train/detection.html) under windows

**Environment:**

sys.platform: win32 (Windows 11)
Python Environment: Conda
Python: 3.9.16 (main, Mar  8 2023, 10:39:24) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
GPU 0,1: NVIDIA GeForce GTX 1080 Ti
CUDA_HOME: C:\Users\demo\.conda\envs\openvino
NVCC: Cuda compilation tools, release 11.7, V11.7.99
MSVC: Microsoft (R) C/C++ Optimizing Compiler Version 19.34.31937 for x64
GCC: n/a
PyTorch: 1.13.1
TorchVision: 0.14.1
OpenCV: 4.7.0
MMCV: 1.7.0
MMCV Compiler: MSVC 193431937
MMCV CUDA Compiler: 11.7
MMDetection: 2.28.1+

**Comment by goodsong81** [comment]
Thank you for the report. By the way, we are not officially supporting the Windows OS yet.
That being said, you may use single process data loader by passing `params learning_parameters.num_workers 0` at the end of training command.
(Try `otx train {template} params -h` for more information)

**Comment by eunwoosh** [comment]
You may meet some error if you use `params learning_parameters.num_workers 0`.
I recommend to modify `num_worker` value in configuration.yaml in your workspace.

**Comment by cansik** [comment]
Thanks for the quick replies, setting the `num_workers` to `0` helped with this problem. It seems that most of the steps work on Windows except setting the symlink after training. Post-tuning and exporting also worked.
