### ISSUE TITLE
"No CUDA runtime is found'" error when running horizontal text detection model

### ISSUE THREAD

**Issue by aljie28** [open-edge-platform/training_extensions#2372]
I encounter this error message 

"""
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-10.2'
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-10.2'
Traceback (most recent call last):
  File "/home/kai/training_extensions/external/mmdetection/tools/export.py", line 27, in <module>
    from mmdet.apis import get_fake_input, init_detector
  File "/home/kai/training_extensions/external/mmdetection/mmdet/apis/__init__.py", line 1, in <module>
    from .fake_input import get_fake_input
  File "/home/kai/training_extensions/external/mmdetection/mmdet/apis/fake_input.py", line 20, in <module>
    from mmdet.datasets.pipelines import Compose
  File "/home/kai/training_extensions/external/mmdetection/mmdet/datasets/__init__.py", line 1, in <module>
    from .builder import DATASETS, PIPELINES, build_dataloader, build_dataset
  File "/home/kai/training_extensions/external/mmdetection/mmdet/datasets/builder.py", line 26, in <module>
    from .dataset_wrappers import ConcatDataset, RepeatDataset
  File "/home/kai/training_extensions/external/mmdetection/mmdet/datasets/dataset_wrappers.py", line 10, in <module>
    from .coco import CocoDataset
  File "/home/kai/training_extensions/external/mmdetection/mmdet/datasets/coco.py", line 18, in <module>
    from mmdet.core import eval_recalls
  File "/home/kai/training_extensions/external/mmdetection/mmdet/core/__init__.py", line 1, in <module>
    from .anchor import *  # noqa: F401, F403
  File "/home/kai/training_extensions/external/mmdetection/mmdet/core/anchor/__init__.py", line 1, in <module>
    from .anchor_generator import (AnchorGenerator, LegacyAnchorGenerator,
  File "/home/kai/training_extensions/external/mmdetection/mmdet/core/anchor/anchor_generator.py", line 7, in <module>
    from mmdet.core.utils.misc import meshgrid
  File "/home/kai/training_extensions/external/mmdetection/mmdet/core/utils/__init__.py", line 3, in <module>
    from .misc import mask2ndarray, multi_apply, unmap
  File "/home/kai/training_extensions/external/mmdetection/mmdet/core/utils/misc.py", line 9, in <module>
    from ..mask.structures import BitmapMasks, PolygonMasks
  File "/home/kai/training_extensions/external/mmdetection/mmdet/core/mask/__init__.py", line 2, in <module>
    from .structures import BaseInstanceMasks, BitmapMasks, PolygonMasks
  File "/home/kai/training_extensions/external/mmdetection/mmdet/core/mask/structures.py", line 8, in <module>
    from mmcv.ops.roi_align import roi_align
  File "/home/kai/training_extensions/models/object_detection/venv/lib/python3.6/site-packages/mmcv/ops/__init__.py", line 1, in <module>
    from .bbox import bbox_overlaps
  File "/home/kai/training_extensions/models/object_detection/venv/lib/python3.6/site-packages/mmcv/ops/bbox.py", line 3, in <module>
    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
  File "/home/kai/training_extensions/models/object_detection/venv/lib/python3.6/site-packages/mmcv/utils/ext_loader.py", line 11, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/kai/training_extensions/models/object_detection/venv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'
Traceback (most recent call last):
  File "export.py", line 41, in <module>
    main()
  File "export.py", line 37, in main
    exporter(ote_args)
  File "/home/kai/training_extensions/ote/ote/modules/exporters/base.py", line 31, in __call__
    self._export_to_openvino(args, tools_dir)
  File "/home/kai/training_extensions/ote/ote/modules/exporters/mmdetection.py", line 51, in _export_to_openvino
    run_through_shell(f'python3 {os.path.join(tools_dir, "export.py")} '
  File "/home/kai/training_extensions/ote/ote/utils/misc.py", line 165, in run_through_shell
    **std_streams_args)
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'python3 /home/kai/training_extensions/external/mmdetection/tools/export.py model.py snapshot.pth export  --opset=11 openvino --input_format BGR' returned non-zero exit status 1.
"""

when I execute this step 

c. Run demo with exported model
python export.py \
   --load-weights ${SNAPSHOT} \
   --save-model-to export

from https://github.com/openvinotoolkit/training_extensions/tree/misc/models/object_detection/model_templates/horizontal-text-detection

I'm using Ubuntu 18.04 
Python 3.6.9
Openvino 4.5.3
CUDA 10.2
![image](https://github.com/openvinotoolkit/training_extensions/assets/139872656/0c66a469-a9d3-4cbe-86a1-4bdafc8e6274)

Does anyone know how to fix it?

**Comment by sungmanc** [comment]
Could you check the CUDA is located at /usr/local ? + your error is not related to the CUDA itself, it is related to the MMCV install. Please check the MMCV installation. 

`ModuleNotFoundError: No module named 'mmcv._ext'`

**Comment by aljie28** [comment]
Here is my pip list

absl-py                 1.4.0
addict                  2.4.0
astroid                 2.5.8
attrs                   22.2.0
cachetools              4.2.4
certifi                 2023.5.7
charset-normalizer      2.0.12
cycler                  0.11.0
Cython                  0.29.35
dataclasses             0.8
decorator               4.4.2
defusedxml              0.7.1
editdistance            0.6.2
flatbuffers             23.5.26
future                  0.18.3
google-auth             2.21.0
google-auth-oauthlib    0.4.6
graphviz                0.19.1
grpcio                  1.48.2
idna                    3.4
importlib-metadata      4.8.3
importlib-resources     5.4.0
iniconfig               1.1.1
isort                   5.10.1
joblib                  1.1.1
jsonschema              3.2.0
jstyleson               0.0.2
kiwisolver              1.3.1
lazy-object-proxy       1.7.1
lxml                    4.9.2
Markdown                3.3.7
matplotlib              3.3.4
mccabe                  0.6.1
mmcv-full               1.3.0
mmdet                   2.9.0    /home/tham/training_extensions/external/mmdetection
mmpycocotools           12.0.3
natsort                 8.2.0
networkx                2.5.1
ninja                   1.11.1
nncf                    1.7.0
numpy                   1.19.5
oauthlib                3.2.2
onnx                    1.10.1
onnxoptimizer           0.2.6
onnxruntime             1.10.0
opencv-python           4.8.0.74
ote                     0.2      /home/tham/training_extensions/ote
packaging               21.3
pandas                  1.1.5
Pillow                  8.4.0
pip                     21.3.1
pkg_resources           0.0.0
pluggy                  1.0.0
Polygon3                3.0.8
protobuf                3.19.6
py                      1.11.0
pyasn1                  0.5.0
pyasn1-modules          0.3.0
pydot                   1.4.2
pylint                  2.7.2
pyparsing               3.1.0
pyrsistent              0.18.0
pytest                  7.0.1
python-dateutil         2.8.2
pytorchcv               0.0.55
pytz                    2023.3
PyYAML                  6.0.1
requests                2.27.1
requests-oauthlib       1.3.1
rsa                     4.9
scikit-learn            0.24.2
scipy                   1.5.4
setuptools              59.6.0
six                     1.16.0
tensorboard             2.10.1
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.1
terminaltables          3.1.10
texttable               1.6.7
threadpoolctl           3.1.0
toml                    0.10.2
tomli                   1.2.3
torch                   1.8.1
torchvision             0.9.1
tqdm                    4.64.1
typed-ast               1.4.3
typing_extensions       4.1.1
urllib3                 1.26.16
Werkzeug                2.0.3
wheel                   0.37.1
wrapt                   1.12.1
yapf                    0.32.0
zipp                    3.6.0

i can see the mmcv-full is installed in it
