### ISSUE TITLE
Error when fine tuning the horizontal text detection

### ISSUE THREAD

**Issue by aljie28** [open-edge-platform/training_extensions#2392]
Hi, I encounter this error when I am running the fine-tuning step in [https://github.com/openvinotoolkit/training_extensions/tree/misc/models/object_detection/model_templates/horizontal-text-detection](url) Step 4.b. Evaluate 

Traceback (most recent call last):
  File "/home/tham/training_extensions/external/mmdetection/tools/test.py", line 260, in <module>
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-10.2'
    main()
  File "/home/tham/training_extensions/external/mmdetection/tools/test.py", line 175, in main
    dataset = build_dataset(cfg.data.test)
  File "/home/tham/training_extensions/external/mmdetection/mmdet/datasets/builder.py", line 108, in build_dataset
    raise RuntimeError(f'Failed to find annotation files that match pattern: '
RuntimeError: Failed to find annotation files that match pattern: /data/horizontal_text_detection/annotation.json
Traceback (most recent call last):
  File "eval.py", line 46, in <module>
    main()
  File "eval.py", line 42, in main
    evaluator(**eval_args)
  File "/home/tham/training_extensions/ote/ote/modules/evaluators/base.py", line 38, in __call__
    self._evaluate_internal(config, snapshot, out, update_config, metrics_functions, **kwargs)
  File "/home/tham/training_extensions/ote/ote/modules/evaluators/base.py", line 62, in _evaluate_internal
    metrics.extend(func(**metric_args))
  File "/home/tham/training_extensions/ote/ote/metrics/horizontal_text_detection/horizontal_text_detection.py", line 68, in coco_eval
    'key': 'f1', 'value': hmean[2] * 100, 'unit': '%', 'display_name': 'F1-score'
IndexError: list index out of range

Can anyone help me to verify, thank you.

**Comment by sungmanc** [comment]
`RuntimeError: Failed to find annotation files that match pattern: /data/horizontal_text_detection/annotation.json`
Please change the dataset that you used. Since we don't guarantee the `misc` branch, it could include the outdated contents.
