### ISSUE TITLE
Why we need a monkey patch for mm* data preprocessors in OTX 2.0

### ISSUE THREAD

**Issue by vinnamkim** [open-edge-platform/training_extensions#2743]
Without monkey patching mm* data preprocessors, we will face `RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!` while running on PytorchLightning Trainer loop with GPU. This is because they cast the input data into `self.device` device (Please see [this link](https://github.com/open-mmlab/mmengine/blob/85c0976bc2434157f786d44cdd8f0fb2955414f0/mmengine/model/base_model/data_preprocessor.py#L60)). The problem here is that PytorchLightning Trainer cannot change their `device` property. The following code is for minimal reproduction about this problem.

```python
from mmseg.models.data_preprocessor import SegDataPreProcessor
import torch
from torch import nn

class MyModel(nn.Module):
    def __init__(self):
        self.preprocessor = SegDataPreProcessor((1, 2, 3), (1, 2, 3))

    def forward(self, data):
        return self.preprocessor(data)


net = MyModel()

# To cuda
net = net.to(device="cuda")

# Input
x = {"inputs": [torch.randn(3, 10, 10).cuda()]}

# Print devices for preprocessor and preprocessor.mean respectively
print(
    "Preprocessor's device:",
    net.preprocessor.device,
    ", Preprocessor.mean's device:",
    net.preprocessor.mean.device,
)

# It will raise an error
y = net(x)
```

It will print
```console
Preprocessor's device: cpu , Preprocessor.mean's device: cuda:0
```
, and raise this error
```console
Traceback (most recent call last):
  File "/home/vinnamki/otx/training_extensions/test_1.py", line 42, in <module>
    y = net(x)
        ^^^^^^
  File "/home/vinnamki/miniconda3/envs/otx-v2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinnamki/miniconda3/envs/otx-v2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinnamki/otx/training_extensions/test_1.py", line 25, in forward
    return self.preprocessor(data)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinnamki/miniconda3/envs/otx-v2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinnamki/miniconda3/envs/otx-v2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinnamki/miniconda3/envs/otx-v2/lib/python3.11/site-packages/mmseg/models/data_preprocessor.py", line 118, in forward
    inputs = [(_input - self.mean) / self.std for _input in inputs]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinnamki/miniconda3/envs/otx-v2/lib/python3.11/site-packages/mmseg/models/data_preprocessor.py", line 118, in <listcomp>
    inputs = [(_input - self.mean) / self.std for _input in inputs]
               ~~~~~~~^~~~~~~~~~~
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

To prevent it, we can monkey patch mm* data preprocessors such as
```python
from mmseg.models.data_preprocessor import SegDataPreProcessor as _SegDataPreProcessor

class SegDataPreProcessor(_SegDataPreProcessor):
    @property
    def device(self):
        try:
            buf = next(self.buffers())
            return buf.device
        except StopIteration:
            return super().device
```

**Comment by vinnamkim** [comment]
We might look back in the future if the upstream (MM*) solves this issue.
