### ISSUE TITLE
OTX v2 action detection "RuntimeError: one_hot is only applicable to index tensor."

### ISSUE THREAD

**Issue by goodsong81** [open-edge-platform/training_extensions#3267]
**Describe the bug**

```console
Traceback (most recent call last):
  File "/home/validation/actions-runner/_work/training_extensions/training_extensions/.tox/perf-benchmark/bin/otx", line 8, in <module>
    sys.exit(main())
  File "/home/validation/actions-runner/_work/training_extensions/training_extensions/.tox/perf-benchmark/lib/python3.10/site-packages/otx/cli/__init__.py", line 17, in main
    OTXCLI()
  File "/home/validation/actions-runner/_work/training_extensions/training_extensions/.tox/perf-benchmark/lib/python3.10/site-packages/otx/cli/cli.py", line 55, in __init__
    self.run()
  File "/home/validation/actions-runner/_work/training_extensions/training_extensions/.tox/perf-benchmark/lib/python3.10/site-packages/otx/cli/cli.py", line 574, in run
    fn(**fn_kwargs)
  File "/home/validation/actions-runner/_work/training_extensions/training_extensions/.tox/perf-benchmark/lib/python3.10/site-packages/otx/engine/engine.py", line 261, in train
    self.trainer.fit(
  File "/home/validation/actions-runner/_work/training_extensions/training_extensions/.tox/perf-benchmark/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "/home/validation/actions-runner/_work/training_extensions/training_extensions/.tox/perf-benchmark/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/validation/actions-runner/_work/training_extensions/training_extensions/.tox/perf-benchmark/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/validation/actions-runner/_work/training_extensions/training_extensions/.tox/perf-benchmark/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 989, in _run
    results = self._run_stage()
  File "/home/validation/actions-runner/_work/training_extensions/training_extensions/.tox/perf-benchmark/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 1035, in _run_stage
    self.fit_loop.run()
  File "/home/validation/actions-runner/_work/training_extensions/training_extensions/.tox/perf-benchmark/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py", line 202, in run
    self.advance()
  File "/home/validation/actions-runner/_work/training_extensions/training_extensions/.tox/perf-benchmark/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py", line 359, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/home/validation/actions-runner/_work/training_extensions/training_extensions/.tox/perf-benchmark/lib/python3.10/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 137, in run
    self.on_advance_end(data_fetcher)
  File "/home/validation/actions-runner/_work/training_extensions/training_extensions/.tox/perf-benchmark/lib/python3.10/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 285, in on_advance_end
    self.val_loop.run()
  File "/home/validation/actions-runner/_work/training_extensions/training_extensions/.tox/perf-benchmark/lib/python3.10/site-packages/lightning/pytorch/loops/utilities.py", line 182, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/home/validation/actions-runner/_work/training_extensions/training_extensions/.tox/perf-benchmark/lib/python3.10/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 127, in run
    batch, batch_idx, dataloader_idx = next(data_fetcher)
  File "/home/validation/actions-runner/_work/training_extensions/training_extensions/.tox/perf-benchmark/lib/python3.10/site-packages/lightning/pytorch/loops/fetchers.py", line 127, in __next__
    batch = super().__next__()
  File "/home/validation/actions-runner/_work/training_extensions/training_extensions/.tox/perf-benchmark/lib/python3.10/site-packages/lightning/pytorch/loops/fetchers.py", line 56, in __next__
    batch = next(self.iterator)
  File "/home/validation/actions-runner/_work/training_extensions/training_extensions/.tox/perf-benchmark/lib/python3.10/site-packages/lightning/pytorch/utilities/combined_loader.py", line 326, in __next__
    out = next(self._iterator)
  File "/home/validation/actions-runner/_work/training_extensions/training_extensions/.tox/perf-benchmark/lib/python3.10/site-packages/lightning/pytorch/utilities/combined_loader.py", line 132, in __next__
    out = next(self.iterators[0])
  File "/home/validation/actions-runner/_work/training_extensions/training_extensions/.tox/perf-benchmark/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/validation/actions-runner/_work/training_extensions/training_extensions/.tox/perf-benchmark/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/home/validation/actions-runner/_work/training_extensions/training_extensions/.tox/perf-benchmark/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/home/validation/actions-runner/_work/training_extensions/training_extensions/.tox/perf-benchmark/lib/python3.10/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/validation/actions-runner/_work/training_extensions/training_extensions/.tox/perf-benchmark/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/validation/actions-runner/_work/training_extensions/training_extensions/.tox/perf-benchmark/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/validation/actions-runner/_work/training_extensions/training_extensions/.tox/perf-benchmark/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/validation/actions-runner/_work/training_extensions/training_extensions/.tox/perf-benchmark/lib/python3.10/site-packages/otx/core/data/dataset/base.py", line 178, in __getitem__
    results = self._get_item_impl(index)
  File "/home/validation/actions-runner/_work/training_extensions/training_extensions/.tox/perf-benchmark/lib/python3.10/site-packages/otx/core/data/dataset/action_detection.py", line 56, in _get_item_impl
    labels=torch.nn.functional.one_hot(
RuntimeError: one_hot is only applicable to index tensor.
```

**Steps to Reproduce**

On the latest releases/2.0.0 (326fddf)
```console
otx train --config src/otx/recipe/action/action_detection/x3d_fastrcnn.yaml --data_root data/action/action_detection/UCF101_ava_5percent --work_dir /tmp/action-det --engine.device gpu --max_epochs 1 --deterministic True --seed 0 --deterministic False
otx test --work_dir /tmp/action-det
```

**Environment:**

- OS: 
- Framework version: 
- Python version:
- OpenVINO version:
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by harimkang** [comment]
no longer support action detection.
