### ISSUE TITLE
OTX v2.1 classification train & test -> "TypeError: otx.algo.classification.efficientnet_b0.EfficientNetB0ForMulticlassCls.<lambda>"

### ISSUE THREAD

**Issue by goodsong81** [open-edge-platform/training_extensions#3310]
**Describe the bug**

```console
Traceback (most recent call last):
  File "/home/songkich/miniconda3/envs/otx-v2/bin/otx", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/mnt/sdb/workarea/otx/src/otx/cli/__init__.py", line 17, in main
    OTXCLI()
  File "/mnt/sdb/workarea/otx/src/otx/cli/cli.py", line 59, in __init__
    self.run()
  File "/mnt/sdb/workarea/otx/src/otx/cli/cli.py", line 518, in run
    self.instantiate_classes()
  File "/mnt/sdb/workarea/otx/src/otx/cli/cli.py", line 337, in instantiate_classes
    self.model = self.instantiate_model(model_config=model_config)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/sdb/workarea/otx/src/otx/cli/cli.py", line 392, in instantiate_model
    model = model_parser.instantiate_classes(Namespace(model=model_config)).get("model")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/songkich/miniconda3/envs/otx-v2/lib/python3.11/site-packages/jsonargparse/_deprecated.py", line 141, in patched_instantiate_classes
    cfg = self._unpatched_instantiate_classes(cfg, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/songkich/miniconda3/envs/otx-v2/lib/python3.11/site-packages/jsonargparse/_core.py", line 1175, in instantiate_classes
    parent[key] = component.instantiate_classes(value)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/songkich/miniconda3/envs/otx-v2/lib/python3.11/site-packages/jsonargparse/_typehints.py", line 533, in instantiate_classes
    value[num] = adapt_typehints(
                 ^^^^^^^^^^^^^^^^
  File "/home/songkich/miniconda3/envs/otx-v2/lib/python3.11/site-packages/jsonargparse/_typehints.py", line 900, in adapt_typehints
    val = adapt_class_type(val, serialize, instantiate_classes, sub_add_kwargs, prev_val=prev_val)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/songkich/miniconda3/envs/otx-v2/lib/python3.11/site-packages/jsonargparse/_typehints.py", line 1123, in adapt_class_type
    return instantiator_fn(val_class, **{**init_args, **dict_kwargs})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/songkich/miniconda3/envs/otx-v2/lib/python3.11/site-packages/jsonargparse/_common.py", line 128, in default_class_instantiator
    return class_type(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/sdb/workarea/otx/src/otx/algo/classification/efficientnet_b0.py", line 91, in __init__
    super().__init__(
  File "/mnt/sdb/workarea/otx/src/otx/core/model/classification.py", line 118, in __init__
    super().__init__(
  File "/mnt/sdb/workarea/otx/src/otx/core/model/classification.py", line 66, in __init__
    super().__init__(
  File "/mnt/sdb/workarea/otx/src/otx/core/model/base.py", line 109, in __init__
    self.optimizer_callable = ensure_callable(optimizer)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/sdb/workarea/otx/src/otx/core/utils/miscellaneous.py", line 15, in ensure_callable
    raise TypeError(func)
TypeError: otx.algo.classification.efficientnet_b0.EfficientNetB0ForMulticlassCls.<lambda>
```

**Steps to Reproduce**

On the latest develop (3266f2424)
```console
otx train --config src/otx/recipe/classification/multi_class_cls/efficientnet_b0_light.yaml --data_root tests/assets/classification_dataset/ --work_dir /tmp/eff-b0 --max_epochs 1
otx test --work_dir /tmp/eff-b0
```

**Environment:**

- OS: 
- Framework version: 
- Python version:
- OpenVINO version:
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by harimkang** [comment]
@goodsong81 I think the feature is currently broken for a while due to a refactoring in the develop branch, which Vinnam will be fixing soon. @vinnamkim 
https://github.com/openvinotoolkit/training_extensions/blob/fb69fcbcc23853537b5db3750e3a9217c80b19b5/src/otx/cli/cli.py#L458

**Comment by vinnamkim** [comment]
I haven't notice it but I have two questions:

1. Why do we use both channel GH issue tab and JIRA system although we already have been using JIRA system across all ODT teams?
2. Why have not been this case not tested by our integration tests?

**Comment by goodsong81** [comment]
> I haven't notice it but I have two questions:
> 
> 1. Why do we use both channel GH issue tab and JIRA system although we already have been using JIRA system across all ODT teams?
> 2. Why have not been this case not tested by our integration tests?

1 -> IMHO, as the OTX is an open source project, we'd better not to mention internal things like team name, Jira ticket numbers, etc. If some kind of consolidation policy needed, please discuss in the team. Anyway, people have been using OTX GH issue tab for externally obvious issues like CLI bugs.

2 -> I agree that this should have been captured in tests.

**Comment by chuneuny-emily** [comment]
fixed
