### ISSUE TITLE
Exported model person-vehicle-bike-detection-2000 error run on MYRIAD device. It's normal?

### ISSUE THREAD

**Issue by teb4** [open-edge-platform/training_extensions#752]
For model person-vehicle-bike-detection-2000 an error occurs on step 
              3. Try a pre-trained model
                 c. Run demo with exported model
 if the device is MYRIAD:

[ INFO ] Initializing Inference Engine...
[ INFO ] Loading network...
[ INFO ] Reading network from IR...
[ INFO ] Use BoxesLabelsParser
[ INFO ] Loading network to MYRIAD plugin...
Traceback (most recent call last):
  File "/home/teb/open_model_zoo/demos/object_detection_demo/python/object_detection_demo.py", line 361, in <module>
    sys.exit(main() or 0)
  File "/home/teb/open_model_zoo/demos/object_detection_demo/python/object_detection_demo.py", line 251, in main
    device=args.device, max_num_requests=args.num_infer_requests)
  File "/home/teb/open_model_zoo/demos/common/python/pipelines/async_pipeline.py", line 90, in __init__
    config=plugin_config, num_requests=max_num_requests)
  File "ie_api.pyx", line 403, in openvino.inference_engine.ie_api.IECore.load_network
  File "ie_api.pyx", line 442, in openvino.inference_engine.ie_api.IECore.load_network
RuntimeError: [ GENERAL_ERROR ] 
/home/jenkins/agent/workspace/private-ci/ie/build-linux-ubuntu18/b/repos/openvino/inference-engine/src/vpu/graph_transformer/src/frontend/frontend.cpp:441 Failed to compile layer "ScatterND_887": unsupported layer type "ScatterNDUpdate"

**Comment by morkovka1337** [comment]
Hi,

I'm afraid we can not help in this situation since we only develop the model. The model is converted by the model optimizer and then is being run in the open model zoo object detection demo. You can create issue in [open_model_zoo](https://github.com/openvinotoolkit/open_model_zoo/) or [openvino](https://github.com/openvinotoolkit/openvino)  repositories.

**Comment by sungmanc** [comment]
Close this issue, please reopen it if there is any problem.
